name: Tangem publish

on:
  push:
    branches:
      - 'release/**'
      - 'master'
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_ANDROID }}

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read version.properties file
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: version.properties
          properties: 'core tangem'

      - name: Echo version.properties
        run: echo "${{ steps.properties.outputs.core }}-${{ steps.properties.outputs.tangem }}"

      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.properties.outputs.core }}-${{ steps.properties.outputs.tangem }}",
              sha: context.sha
            })
